### ISSUE TITLE
Testing pushbullet

### ISSUE THREAD

**Issue by d1mf** [pernodpepper/SSLChecker#2]
Hello. You make a very interesting project. I install the dashboard and see this working.
I have questions:
1) How is testing working pushbullet?
2) If I run cron.php I have an error

    2018-09-06 05:18:25pm<br><br>PHP Notice:  Undefined variable: x_title in lib/functions.php on line 116
PHP Warning:  Cannot modify header information - headers already sent by (output started at cron.php:1) in lib/functions.php on line 134

**Comment by pernodpepper** [comment]
I will look into that soon. Thanks for your feedback.

**Comment by d1mf** [comment]
Good. I need a close ticket or wait for an answer?

**Comment by pernodpepper** [comment]
SMTP mail support has been added.

**Comment by d1mf** [comment]
Hello.
// Notification Settings
$useMail = true;
$usePush = false;
This need true(if enable) correct?

**Comment by pernodpepper** [comment]
Yes true for enabling

**Comment by d1mf** [comment]
How testing? need ssl expires?
http://prntscr.com/kxiwvz

**Comment by pernodpepper** [comment]
Sorry i forgot to add some sort of a test button. I'll add it within 24
hours. Just make sure your email details are good then it will work for
sure.

For your information
It sends a notification:
- 30 days before
- 20 days before
- 10 days before
- 1 day before

**Comment by d1mf** [comment]
I add expires ssl. I did not see working pushbullet or email. I have a mail server, I change the port to 25(TLS support) and testing https://smtp2go.com 587 port. Clean.
This full list error cron.php( if this help you)

2018-09-23 12:05:38am<br><br>2018-09-23 12:05:39am<br><br>2018-09-23 12:05:39am<br><br>2018-09-23 12:05:40am<br><br>2018-09-23 12:05:41am<br><br>2018-09-23 12:05:41am<br><br>2018-09-23 12:05:42am<br><br>2018-09-23 12:05:43am<br><br>2018-09-23 12:05:44am<br><br>2018-09-23 12:05:45am<br><br>

PHP Notice: Undefined variable: trigger in /var/www//lib/functions.php on line 170
PHP Notice: Undefined variable: trigger in /var/www//lib/functions.php on line 173
PHP Warning: Cannot modify header information - headers already sent by (output started at /var/www//cron.php:1) in /var/www//lib/functions.php on line 143
PHP Notice: Undefined variable: trigger in /var/www//lib/functions.php on line 170
PHP Notice: Undefined variable: trigger in /var/www//lib/functions.php on line 173
PHP Warning: Cannot modify header information - headers already sent by (output started at /var/www//cron.php:1) in /var/www//lib/functions.php on line 143
PHP Notice: Undefined variable: trigger in /var/www//lib/functions.php on line 170
PHP Notice: Undefined variable: trigger in /var/www//lib/functions.php on line 173
PHP Warning: Cannot modify header information - headers already sent by (output started at /var/www//cron.php:1) in /var/www//lib/functions.php on line 143
PHP Notice: Undefined variable: trigger in /var/www//lib/functions.php on line 170
PHP Notice: Undefined variable: trigger in /var/www//lib/functions.php on line 173
PHP Warning: Cannot modify header information - headers already sent by (output started at /var/www//cron.php:1) in /var/www//lib/functions.php on line 143
PHP Notice: Undefined variable: trigger in /var/www//lib/functions.php on line 170
PHP Notice: Undefined variable: trigger in /var/www//lib/functions.php on line 173
PHP Warning: Cannot modify header information - headers already sent by (output started at /var/www//cron.php:1) in /var/www//lib/functions.php on line 143
PHP Notice: Undefined variable: trigger in /var/www//lib/functions.php on line 170
PHP Notice: Undefined variable: trigger in /var/www//lib/functions.php on line 173
PHP Warning: Cannot modify header information - headers already sent by (output started at /var/www//cron.php:1) in /var/www//lib/functions.php on line 143
PHP Notice: Undefined variable: trigger in /var/www//lib/functions.php on line 170
PHP Notice: Undefined variable: trigger in /var/www//lib/functions.php on line 173
PHP Warning: Cannot modify header information - headers already sent by (output started at /var/www//cron.php:1) in /var/www//lib/functions.php on line 143
PHP Notice: Undefined variable: trigger in /var/www//lib/functions.php on line 170
PHP Notice: Undefined variable: trigger in /var/www//lib/functions.php on line 173
PHP Warning: Cannot modify header information - headers already sent by (output started at /var/www//cron.php:1) in /var/www//lib/functions.php on line 143
PHP Notice: Undefined variable: trigger in /var/www//lib/functions.php on line 170
PHP Notice: Undefined variable: trigger in /var/www//lib/functions.php on line 173
PHP Warning: Cannot modify header information - headers already sent by (output started at /var/www//cron.php:1) in /var/www//lib/functions.php on line 143
PHP Notice: Undefined variable: trigger in /var/www//lib/functions.php on line 170
PHP Notice: Undefined variable: trigger in /var/www//lib/functions.php on line 173
PHP Warning: Cannot modify header information - headers already sent by (output started at /var/www//cron.php:1) in /var/www//lib/functions.php on line 143

**Comment by pernodpepper** [comment]
0.6.3 has now been released with E-mail testing option in config.

**Comment by d1mf** [comment]
Thanks.  Test pushbullet working and email no(not sure maybe problem config my email server)
any case I have 1 ssl expire and pushbullet not send a notification.
My server have 25 port TLS this good?

**Comment by d1mf** [comment]
wow. test email working!

**Comment by d1mf** [comment]
test working. notification expire ssl not

**Comment by pernodpepper** [comment]
If you add an already expired SSL it won't work. Make sure you renew the SSL first and then add it to the checker.

Thanks for letting me know. If you have any new issues please create a new issue.

**Comment by d1mf** [comment]
Thanks for the new answer. Ok, I later test and ping you. Function test pushubullet and email 100% working

**Comment by d1mf** [comment]
http://prntscr.com/l3s7tn
I not have alert in email or pushbullet

**Comment by d1mf** [comment]
alert 20 days working!
