### ISSUE TITLE
Can't add a server

### ISSUE THREAD

**Issue by Niii** [pernodpepper/SSLChecker#4]
Hi,

I just found your project and wanna try your interface but I'm unable to add a server.
All seems good, no error message on add server page, but there still nothing on mysql databse.

- git clone master branch
- import github.sql into database
- disable google captcha to be able to login
- Try to add server, success on web page but nothing in table "servers"

Can you take a look or advise me ?

Apache 2.4.38 / PHP 7.4.6

**Comment by Niii** [comment]
Error was in the insert request :
`$sql = "INSERT INTO servers (id, name, port, authority, state) VALUES ('','$name','$port','First update can take up to 24 hours.','4')";`

Without id specified (automatically generated by mysql) it works :
`$sql = "INSERT INTO servers (name, port, authority, state) VALUES ('$name','$port','First update can take up to 24 hours.','4')";`

**Comment by pernodpepper** [comment]
Thank you for solving it. I've changed the code and created a new release. Currently I don't have much time to work on this project. It worked fine on my webserver but it probably has something to do with the database server. I am using MariaDB.
